name: Run BSD Tests

on:
  push:
    branches:
      hcarter/1-convert-cirrus-yml-to-github-actions
      TheCapableHub
      cheri
  pull_request_target:
    types: [ opened, reopened, edited, synchronize ]

env:
  FREEBSD_VERSION: 14.3
  CPUS: 8
  MEM: 8192

jobs:
  matrix:
    runs-on: self-hosted # ubuntu-latest
    env:
      PKG_LEVEL: 1
    steps:
      - uses: actions/checkout@v4
      - name: "amd64-llvm16 World and kernel build and boot smoke test"
        env:
          TARGET: amd64
          TARGET_ARCH: amd64
          TOOLCHAIN: llvm16
          TOOLCHAIN_PKG: ${TOOLCHAIN}-lite
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ env.FREEBSD_VERSION }}
          mem: ${{ env.MEM }}
          cpu: ${{ env.CPUS }}
          envs: "TARGET TARGET_ARCH TOOLCHAIN TOOLCHAIN_PKG"
          usesh: true
      # - name: "amd64-llvm17 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: amd64
      #     TARGET_ARCH: amd64
      #     TOOLCHAIN: llvm17
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}-lite
      # - name: "amd64-llvm18 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: amd64
      #     TARGET_ARCH: amd64
      #     TOOLCHAIN: llvm18
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}-lite
      # - name: "amd64-llvm19 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: amd64
      #     TARGET_ARCH: amd64
      #     TOOLCHAIN: llvm19
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}-lite
      # - name: "amd64-gcc14 World and kernel build and boot smoke test (FreeBSD repo)"
      #   env:
      #     TARGET: amd64
      #     TARGET_ARCH: amd64
      #     TOOLCHAIN: amd64-gcc14
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      #     EXTRA_MAKE_FLAGS: -s

      # - name: "arm64-llvm16 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: arm64
      #     TARGET_ARCH: aarch64
      #     TOOLCHAIN: llvm16
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      # - name: "arm64-llvm17 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: arm64
      #     TARGET_ARCH: aarch64
      #     TOOLCHAIN: llvm17
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      # - name: "arm64-llvm18 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: arm64
      #     TARGET_ARCH: aarch64
      #     TOOLCHAIN: llvm18
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      # - name: "arm64-llvm19 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: arm64
      #     TARGET_ARCH: aarch64
      #     TOOLCHAIN: llvm19
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      # - name: "amd64-gcc12 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: amd64
      #     TARGET_ARCH: amd64
      #     TOOLCHAIN: amd64-gcc12
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      #     EXTRA_MAKE_FLAGS: -s

      # - name: "amd64-gcc13 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: amd64
      #     TARGET_ARCH: amd64
      #     TOOLCHAIN: amd64-gcc13
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      #     EXTRA_MAKE_FLAGS: -s

      # - name: "amd64-gcc14 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: amd64
      #     TARGET_ARCH: amd64
      #     TOOLCHAIN: amd64-gcc14
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      #     EXTRA_MAKE_FLAGS: -s

      # - name: "aarch64-gcc12 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: arm64
      #     TARGET_ARCH: aarch64
      #     TOOLCHAIN: aarch64-gcc12
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      #     EXTRA_MAKE_FLAGS: -s

      # - name: "aarch64-gcc13 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: arm64
      #     TARGET_ARCH: aarch64
      #     TOOLCHAIN: aarch64-gcc13
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      #     EXTRA_MAKE_FLAGS: -s

      # - name: "aarch64-gcc14 World and kernel build and boot smoke test"
      #   env:
      #     TARGET: arm64
      #     TARGET_ARCH: aarch64
      #     TOOLCHAIN: aarch64-gcc14
      #     TOOLCHAIN_PKG: ${TOOLCHAIN}
      #     EXTRA_MAKE_FLAGS: -s
    
