#!/bin/sh


# Handle CLI arguments
for arg in "$@"; do
    case "$arg" in
        setup_script)
            setup_script
            ;;
        build_world_script)
            build_world_Script
            ;;
        build_kernel_script)
            build_kernel_script
            ;;
        package_script)
            package_script
            ;;
        package_check_script)
            package_check_script
            ;;
        test_script)
            test_script
            ;;
        make_sysent_script)
            make_sysent_script
            ;;
        include_ldirs_script)
            include_ldirs_script
            ;;
        makeman_script)
            makeman_script
            ;;
        post_script)
            post_script
            ;;
        help|-h)
            echo "Usage: $0 [SCRIPT]"
            echo ""
            echo "Options:"
            echo "  setup_script      "
            echo "  build_world_script         "
            echo "  build_kernel_script"
            echo "  package_script"
            echo "  package_check_script"
            echo "  test_script"
            echo "  make_sysent_script"
            echo "  include_ldirs_script"
            echo "  makeman_script"
            echo "  post_script"
            echo ""
            echo "Note: At least one feature must be specified."
            exit 0
            ;;
        *)
            echo "Warning: Unknown argument '$arg' ignored." >&2
            ;;
    esac
done


function setup_script()
{
    uname -a
    gpart show
    df -m
    pkg --version
    pw useradd -n user -m
    mkdir -p /usr/obj/$(pwd -P)
    chown user:user /usr/obj/$(pwd -P)
    su user -c "git config --global --add safe.directory $(pwd -P)"
}

function build_world_script()
{
    su user -c "make -j$(nproc) ${EXTRA_MAKE_FLAGS}
 CROSS_TOOLCHAIN=${TOOLCHAIN}
 WITHOUT_TOOLCHAIN=yes buildworld"
}

function build_kernel_script()
{
    su user -c "make -j$(nproc) CROSS_TOOLCHAIN=${TOOLCHAIN}
 WITHOUT_TOOLCHAIN=yes buildkernel"
}

function package_script()
{
    su user -c "make -j$(nproc) CROSS_TOOLCHAIN=${TOOLCHAIN} WITHOUT_TOOLCHAIN=yes packages"
}

function package_check_script()
{
    su user -c "/usr/libexec/flua tools/pkgbase/metalog_reader.lua -c /usr/obj/$(pwd -P)/${TARGET}
.${TARGET_ARCH}
/worldstage/METALOG"
}

function test_script()
{
    sh .cirrus-ci/pkg-install.sh qemu-nox11
    sh tools/boot/ci-qemu-test.sh
}

function make_sysent_script()
{
  # Check that make sysent results were committed if required
    make sysent
    if ! git diff --exit-code; then printf "\n>>> Generated sysent files not updated, run make sysent <<<\n"; false; fi
}

function include_ldirs_script()
{
  # Check that includes/Makefile refers to existing directories
    if ! make -C include/ check-ldirs; then printf "\n>>> include/Makefile lists nonexistant directories <<<\n"; false; fi
}

function makeman_script()
{
  # Check that the committed src.conf.5 matches the one generated by
  # tools/build/options/makeman (modulo the date which always updates)
  # XXX: This script is slow so keep it last
    (make makeman 2> /tmp/makeman.out); cat /tmp/makeman.out
    if ! git diff --exit-code --ignore-matching-lines "^.Dd" share/man/man5/src.conf.5; then printf "\n>>> src.conf.5 was not updated as required <<<\n"; false; fi
    if grep -q "no description found" /tmp/makeman.out; then printf "\n>>> Missing description files <<<\n"; false; fi
}

function post_script()
{
    df -m
    du -m -s /usr/obj
}